### ISSUE TITLE
Fedora providing unstable flatpak-builder is triggerring issues

### ISSUE THREAD

**Issue by tytan652** [flatpak/flatpak-github-actions#168]
While OBS 30.0.0 was released, Fedora was providing 1.3.3.

Now with 30.0.1, it was 1.3.5, this version (with 1.3.4) changes how screenshots are handled which breaks the actions for publishing.

My take is that if Fedora does not change their stance on providing unstable version of flatpak-builder, using Fedora for this actions looks like a bad idea.

The run https://github.com/obsproject/obs-studio/actions/runs/7156924103/job/19487176553

```
Committing screenshots...
Uploading artifact...
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
/usr/bin/ostree commit --repo=repo --canonical-permissions --branch=screenshots/x86_64 flatpak_app/screenshots
error: opendir(flatpak_app/screenshots): No such file or directory
/__w/_actions/flatpak/flatpak-github-actions/0ab9dd6a6afa6fe7e292db0325171660bf5b6fdf/flatpak-builder/dist/index.js:7912
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^

Error: The process '/usr/bin/ostree' failed with exit code 1
    at ExecState._setResult (/__w/_actions/flatpak/flatpak-github-actions/0ab9dd6a6afa6fe7e292db0325171660bf5b6fdf/flatpak-builder/dist/index.js:7912:25)
    at ExecState.CheckComplete (/__w/_actions/flatpak/flatpak-github-actions/0ab9dd6a6afa6fe7e292db0325171660bf5b6fdf/flatpak-builder/dist/index.js:7895:18)
    at ChildProcess.<anonymous> (/__w/_actions/flatpak/flatpak-github-actions/0ab9dd6a6afa6fe7e292db0325171660bf5b6fdf/flatpak-builder/dist/index.js:7789:27)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

**Comment by bbhtt** [comment]
@kalev said it might not be feasible to downgrade flatpak-builder to 1.2.3 (the libsoup3 port happened, and I think fedora plans on removing libsoup2)

So, the options are I think to switch to Debian/Arch both of which ship 1.2.3 or build `flatpak-builder` matching with what is in `org.flatpak.Builder`

**Comment by kalev** [comment]
flatpak-builder 1.4.0 stable release was just released and it's on it's way to Fedora's updates-testing repo now. Not sure if it helps with this issue in any way though.

**Comment by bilelmoussaoui** [comment]
we no longer depend on fedora's flatpak-builder nor provide any images ourselves.
